language: go
go:
- "1.14.x"

addons:
  apt:
    packages:
    - python3
    - python3-pip

go_import_path: github.com/pfnet-research/k8s-cluster-simulator

before_install:
- export PATH=$GOPATH/bin:$PATH

install:
- go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
- go get -u github.com/mattn/goveralls

script:
- make lint test coverage
- make e2e # don't merge with the above line
- python3 ./scripts/license/check.py -v

after_success:
- goveralls -coverprofile=.profile.cov -service=travis-ci
