# Log level defined by sirupsen/logrus.
# Optional (default: info)
logLevel: debug

# Interval duration for scheduling and updating the cluster, in seconds.
# Optional (default: 10)
tick: 10

# Metrics of simulated kubernetes cluster is written to a file at this path.
# Optional (default: not to write metrics to a file)
metricsFile: kubesim.log

# Metrics of simulated kubernetes cluster is written to this port on localhost.
# Optional (default: not to write metrics to a port)
metricsPort: 10255

# apiPort: 10250

# Start time at which the simulation starts, in RFC3339 format.
# Optional (default: now)
startClock: 2019-01-01T00:00:00+09:00

# Cluster configration
cluster:
  nodes:
  - namespace: default
    name: node-0
    capacity:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1
      pods: 2
    labels:
      beta.kubernetes.io/os: simulated
  - namespace: default
    name: node-1
    capacity:
      cpu: 8
      memory: 16Gi
      nvidia.com/gpu: 2
      pods: 4
    labels:
      beta.kubernetes.io/os: simulated
